version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/Istanbul
    open-pull-requests-limit: 10
    assignees:
      - kadirbelkuyu
    labels:
      - dependencies
      - go
    commit-message:
      prefix: deps
      include: scope
    groups:
      kubernetes:
        patterns:
          - k8s.io/*
        update-types:
          - minor
          - patch
      minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/Istanbul
    open-pull-requests-limit: 5
    assignees:
      - kadirbelkuyu
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
      include: scope
